### ISSUE TITLE
the css style for .cropper-point.point-se had written Reverse！！！

### ISSUE THREAD

**Issue by denghuiquan** [fengyuanchen/cropper#521]
```css
.cropper-point.point-se:before {
  position: absolute;
  right: -50%;
  bottom: -50%;
  display: block;
  width: 200%;
  height: 200%;
  content: " ";
  background-color: #39f;
  filter: alpha(opacity=0); 
  opacity: 0;
}
@media (min-width: 768px) {
  .cropper-point.point-se {
    width: 15px;
    height: 15px;
  }
}
@media (min-width: 992px) {
  .cropper-point.point-se {
    width: 10px;
    height: 10px;
  }
}
@media (min-width: 1200px) {
  .cropper-point.point-se {
    width: 5px;
    height: 5px;
    filter: alpha(opacity=75); 
    opacity: .75;
  }
}
```
