### ISSUE TITLE
smarter responsive?

### ISSUE THREAD

**Issue by makc** [fengyuanchen/cropper#524]
Can the cropper be told to not waste the space on top / below the image? What would I add to the code [here](http://jsfiddle.net/nxqkvcp5/) to lose this space:

![screen shot 2015-11-25 at 18 12 54](https://cloud.githubusercontent.com/assets/242577/11404127/ad6e3ef8-93a0-11e5-9389-27d3a8d1e3dc.png)

**Comment by makc** [comment]
Tried ["example 3"](http://jsfiddle.net/nxqkvcp5/1/) from [here](http://fengyuanchen.github.io/cropper/v1.0.0/) - these areas became way smaller, but not gone:
![screen shot 2015-11-25 at 20 17 53](https://cloud.githubusercontent.com/assets/242577/11407224/bbb59e64-93b1-11e5-9eb0-064d689f1c4f.png)
What's even more disturbing is that resizing the window back and forth adds random space to the container:
![screen shot 2015-11-25 at 20 18 24](https://cloud.githubusercontent.com/assets/242577/11407243/d6b85fb2-93b1-11e5-9842-e6444bd4af20.png)

**Comment by makc** [comment]
so, for now I masked the issue with following css magic:
```css
.cropper-bg {
    background-image: none;
}
.cropper-canvas {
    background-color: black;
}
.cropper-canvas img {
    opacity: 0.5;
}
.cropper-modal {
    background-color: transparent;
}
```
and I am not able to use responsive mode. please advise.

**Comment by fengyuanchen** [comment]
First, you should keep the image responsive, so set CSS like this:
```css
.img-container {
  width: 100%;
}

.img-container img {
  max-width: 100%;
}
```
Then start the cropper.
