### ISSUE TITLE
how to remove the dead zone?

### ISSUE THREAD

**Issue by Spocher** [fengyuanchen/cropper#656]
tell me how to remove the dead zone, resulting in a preview image before cropping?
![image](https://cloud.githubusercontent.com/assets/18357305/14399625/4bec9d2a-fe10-11e5-8450-2c31a8556267.jpeg)
dead zones I noted in the screenshot "this".

**Comment by YamiOdymel** [comment]
Change the view mode?

Checkout the 'VM3' button at the right side menu.

[http://fengyuanchen.github.io/cropperjs/](http://fengyuanchen.github.io/cropperjs/)

**Comment by fengyuanchen** [comment]
If you had read [this part of the documentation](https://github.com/fengyuanchen/cropper#usage), you will not get this problem.

Just a CSS problem:

```css
/* Limit image width to avoid overflow the container */
img {
  max-width: 100%;
}
```
