### ISSUE TITLE
set container height..?

### ISSUE THREAD

**Issue by bilginnet** [fengyuanchen/cropper#833]
i want to set container height to canvas height in modal?
i have custom modal. when i create cropper in modal my view like this in added image

![crop](https://cloud.githubusercontent.com/assets/8385372/21718748/161376a4-d422-11e6-906f-db0d7ccae352.jpg)

i want to set contianer height to canvas height. Becouse my modal height getting long when i load big image in modal ..

and my code is here 

        $image.cropper({
            aspectRatio: myAspectRatio
            viewMode: 2,            
            autoCropArea: 0.5,            
            built: function () {
                croppable = true;                
            }
        });

I am sorry for my english;

**Comment by fengyuanchen** [comment]
Just set the follow styles:

```css
img {
  max-width: 100%; /* This rule is very important, please do not ignore this! */
}
```
