### ISSUE TITLE
Missing maxHeight and maxWidth options

### ISSUE THREAD

**Issue by zeromancer1972** [fengyuanchen/cropper#841]
There was an issue with that before (https://github.com/fengyuanchen/cropper/issues/816) but the opener closed it by himself, so I create a new one:
It would be helpful if the cropping area could support max height and width (as it does with min height and width).
Thanks - its a neat plugin!

**Comment by fengyuanchen** [comment]
```css
.img-container {
  width: 480px; /* use this as the maxWidth */
  height: 480px; /* use this as the maxHeight */
}
```
