### ISSUE TITLE
version upgrade 3.0.0-beta to 3.0.0-rc 

### ISSUE THREAD

**Issue by hasanmumin** [fengyuanchen/cropper#879]
Hi, i try to version upgrade  beta to rc, cropper is not stretch the parent. This only happens on android device.Width and height seem to be calculating incorrectly.

Version 3.0.0-beta
<img width="526" alt="screen shot 2017-04-27 at 09 00 39" src="https://cloud.githubusercontent.com/assets/6329984/25470078/e81ac2ee-2b28-11e7-9749-f57ed479753d.png">

Version 3.0.0-rc 
<img width="467" alt="screen shot 2017-04-27 at 09 00 52" src="https://cloud.githubusercontent.com/assets/6329984/25470095/0477f57e-2b29-11e7-8cdb-eb7b43b45430.png">

**Comment by fengyuanchen** [comment]
Just set the width of your image and image container to `100%`:

```css
.img-container {
  width: 100%;
}

.img-container > img {
  width: 100%;
}
```
