### ISSUE TITLE
Facial guidelines

### ISSUE THREAD

**Issue by ghandic** [fengyuanchen/cropper#980]
Hi,

Great library btw! 

I added this to my css for facial guidelines, it might be useful to add that as an option for users

```css
.cropper-dashed.dashed-v, 
.cropper-dashed.dashed-h {
      border: 3px dashed white;
      height: 77%;
      left: 10%;
      top: 10%;
      width: 80%;
      border-radius: 50% 50% 50% 50% / 40% 40% 60% 60%;
}
```
